# This is a basic workflow to help you get started with Actions

name: styleguide-action
author: Ivan Grekov
description: build visual documentation on github pages for your React.JS UI component library based on Styleguide

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    inputs:
      username:
        description: 'Github username'
        required: true
      password:
         description: 'Github token from secrets'
        required: true
      remoteUrl:
        description: 'Full remote url of repository to push'
        required: false
        default: '12.18.3'
      nodeVersion:
        description: 'Version of NodeJS to run'
        required: false
        default: '12.18.3'
      pathFolderName:
        description: 'temporary path, which you will use for build & deploy'
        required: false
        default: 'Docs'
    
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: $INPUT_NODE_VERSION
          
      # install deps
      - name: Install JavaScript Dependencies 
      env:
      - run: yarn install
      - run: yarn styleguide --buildDir ./$INPUT_PATH_FOLDER_NAME
        
      # depl
      - name: GitHub Pages Deploy
        uses: appleboy/gh-pages-action@v0.0.2
        with:
          username: ${{ INPUT_USERNAME }}
          password: ${{ INPUT_PASSWORD }}
          remote_url: $INPUT_REMOTE_URL
